global: implements base of automated circulation system
lauren-d/invenio-sip2 pull request #1
Opened 2020-05-15 20:48 UTC by lauren-d

* Adds configuration to decrypt and route seflcheck message.
    * Adds sockets server to listen client's request.
    * Creates CLI to launch the SIP2 server.
    * Adds exchange api class to process socket events.
    * Adds actions machine to resolve selfcheck messages.
    * Implements authentication commands.
    * Implements automated circulation system status commannd.
    * Creates tests.

Co-Authored-by: Lauren-D <laurent.dubois@itld-solutions.be>

2020-05-19 12:01 UTC, zannkukai commented on invenio_sip2/actions/actions.py
> +            # for the current client may be we can use redis cache to store
typo "may be" --> "maybe"

2020-05-19 12:06 UTC, zannkukai commented on invenio_sip2/actions/actions.py
> +        return str(response_message)
could be merge in one instruction

2020-05-19 12:48 UTC, zannkukai requested changes

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/actions/actions.py
> +        return str(response_message)
Could be merge in one instruction

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/actions/actions.py
> +        return str(response_message)
one instruction ?

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/actions/base.py
> +            return func(*args, **kwargs)
What's happen if conditions is not success ? The decorator do nothing ? Maybe it will raise an error.

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/actions/base.py
> +    # TO DO: Use enum for manage command
Is this comment still usefull as you already use Enum ?

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/api.py
> +        if len(txt) == 0:
you can write `if not txt:` ... maybe less human readable

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/api.py
> +                break
You can merge all these line using filter : `for part in filter(None, text.split('|'):`

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/api.py
> +        ]) or []
you cannot return `[]` otherwise the method `next` from 'get_variable_field_by_name' will raise an `TypeError: 'list' object is not an iterator`

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/ext.py
> +            _cls = action.pop("action", Action)
maybe better with single quote instead of double quotes

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/ext.py
> +        return self.fixed_fields
😝Java mind ! No need to create a getter function in python ;-) you can just call `my_message.fixed_files`

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/helpers.py
> +            self.length, self.label)
Second return is unrelevant

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/server.py
> +        print("listening on", (self.host, self.port))
maybe better to use `logging` library in next US ?

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/server.py
> +        print('remove client', client)
Add a `#TODO` to easily find this method in next PR ?

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/server.py
> +        elif mode == "rw":
maybe use single quotes

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/server.py
> +            print("sending", repr(self._send_buffer), "to", self.addr)
add spaces after 'sending' and both sides of 'to'

2020-05-19 12:48 UTC, zannkukai commented on invenio_sip2/server.py
> +        return False
you can just write `return len(test) > 1 and ....`

2020-05-19 13:21 UTC, lauren-d commented on invenio_sip2/actions/actions.py
> +            # for the current client may be we can use redis cache to store
done

2020-05-19 13:21 UTC, lauren-d commented on invenio_sip2/actions/actions.py
> +        return str(response_message)
done

2020-05-19 13:21 UTC, lauren-d commented on invenio_sip2/actions/actions.py
> +        return str(response_message)
done

2020-05-19 13:22 UTC, lauren-d commented on invenio_sip2/actions/base.py
> +    # TO DO: Use enum for manage command
removed

2020-05-19 13:22 UTC, lauren-d commented on invenio_sip2/actions/base.py
> +            return func(*args, **kwargs)
to do...

2020-05-19 13:22 UTC, lauren-d commented on invenio_sip2/server.py
> +        print("listening on", (self.host, self.port))
yes

2020-05-19 13:23 UTC, lauren-d commented on invenio_sip2/server.py
> +        elif mode == "rw":
done

2020-05-19 13:23 UTC, lauren-d commented on invenio_sip2/server.py
> +        print('remove client', client)
done

2020-05-19 13:23 UTC, lauren-d commented on invenio_sip2/server.py
> +        return False
done

2020-05-19 13:26 UTC, lauren-d commented on invenio_sip2/server.py
> +            print("sending", repr(self._send_buffer), "to", self.addr)
print method adds a single space by default to separing multiple arguments

2020-05-19 13:27 UTC, lauren-d commented on invenio_sip2/api.py
> +        if len(txt) == 0:
done

2020-05-19 13:35 UTC, lauren-d commented on invenio_sip2/api.py
> +                break
done

2020-05-19 13:35 UTC, lauren-d commented on invenio_sip2/ext.py
> +            _cls = action.pop("action", Action)
done

2020-05-19 13:35 UTC, lauren-d commented on invenio_sip2/ext.py
> +        return self.fixed_fields
done

2020-05-19 13:36 UTC, lauren-d commented on invenio_sip2/helpers.py
> +            self.length, self.label)
done

2020-05-20 07:35 UTC, benerken approved these changes

2020-05-20 12:05 UTC, lauren-d commented on invenio_sip2/api.py
> +        ]) or []
done

2020-05-20 12:15 UTC, zannkukai approved these changes

2020-05-20 12:15 UTC, zannkukai commented on invenio_sip2/api.py
> +        ]) or []
You could resolve this problem using an `yield` statement. Each function using a yield always return a generator (python tricks) even if yield statement is never reached. Yield return a generator and your problem are solved ;-)

2020-05-24 10:25 UTC, BadrAly approved these changes
Job well done

2020-05-24 17:17 UTC, merged